name: Deploy Snapshot

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        distribution: 'zulu'
        java-version: 11
        cache: 'maven'
        server-id: github
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD

    - name: deploy snapshot (github packages)
      if: github.ref == 'refs/heads/master'
      env:
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        MAVEN_USERNAME: ${{ secrets.GITHUB_ACTOR }}
        MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      run: ./mvnw --batch-mode -Dgpg.passphrase=$GPG_PASSPHRASE -DskipTests deploy